repos:
-   repo: local
    hooks:
      - id: isort
        name: "Sort imports"
        entry: .bin/isort
        language: script
        files: '.*.py$'
        exclude: ".*/templates"

      - id: black
        name: "Make it black"
        entry: .bin/black
        language: script
        files: '.*.py$'
        exclude: ".*/templates"

      - id: autoflake
        name: "Autoflake"
        entry: .bin/autoflake
        language: script
        files: '.*.py$'
        exclude: ".*/templates"

      - id: check ci
        name: "Check CI"
        entry: .bin/check_ci
        language: script
        files: '.circleci/config.yml$'
        exclude: ".*/templates"
